### ISSUE TITLE
PDF Bookmarks/Outlines/Table of Content Support

### ISSUE THREAD

**Issue by schwrzstrbn** [HollowMan6/mdbook-pdf#1]

**Comment by HollowMan6** [comment]
You mean the pdf bookmarks/outlines? No, and I had also explained this in the README common Issues part 3.

> 3. Can you add the bookmark to the PDF reflecting the Table of Contents, just like what [wkhtmltopdf](https://wkhtmltopdf.org/) supported?

>
> This should be realized by Chromium, and an issue has already been filed for this [here](https://bugs.chromium.org/p/chromium/issues/detail?id=781797).

**Comment by HollowMan6** [comment]
Other helpful links:
- https://github.com/puppeteer/puppeteer/issues/1778
- https://bugs.chromium.org/p/chromium/issues/detail?id=840455
- https://github.com/isneezy/pdf-generator-service

**Comment by HollowMan6** [comment]
Hi! Finally support for the bookmark/outline of the PDF file is available now([mdbook-pdf-outline](https://pypi.org/project/mdbook-pdf-outline/)). It is written in Python and is another backend for `mdbook` and should be used with `mdbook-pdf` and the [mdbook version](https://github.com/rust-lang/mdBook/pull/1738) mentioned in [Common Issues 2](https://github.com/HollowMan6/mdbook-pdf#common-issues) for fixing the broken links in `print.html`.

You can install this backend by `pip install mdbook-pdf-outline`.

Remember to put the following to ***the end of*** your `book.toml`, ***after [output.pdf]***:

```toml
[output.pdf-outline]
```

If you want to use the table of content just like the one shown in the `print.html` page for PDF file, you can leave the `book.toml` as it is.

If you prefer to use the table of content just like the one generated by `wkhtmltopdf` (generate entries based on the headings), you can turn on the `like-wkhtmltopdf` option by using the following to your `book.toml`:

```toml
[output.pdf-outline]
like-wkhtmltopdf = true
```

You can find the outlined version at `book/pdf-outline/output.pdf`.

Todos:
It would be great if we can rewrite `mdbook-pdf-outline` into rust, but I can hardly find a proper pdf library in rust that supports [named destinations](https://evermap.com/Tutorial_ABM_Destinations.asp), [lopdf](https://github.com/J-F-Liu/lopdf) is a [promising one](https://github.com/J-F-Liu/lopdf/pull/211), let's wait for it to release the new feature.

**Comment by HollowMan6** [comment]
Samples of PDFs with table of content: https://github.com/HollowMan6/mdbook-pdf/actions/runs/3789636358
