### ISSUE TITLE
Help with mdbook-outline-pdf failure?

### ISSUE THREAD

**Issue by GeoffMurray** [HollowMan6/mdbook-pdf#11]
I'm sure I'm just doing something silly. Wondering if you could suggest something I could look at to get this working. 

The mdbook-pdf section works fine, and generates the expected PDF. 

When I tried to add the mdbook-outline-pdf processing, I get a failure. 

I've attached the raw log. Is there anything else I could provide that would be helpful? 

[mdbookrawLog.txt](https://github.com/HollowMan6/mdbook-pdf/files/10693386/mdbookrawLog.txt)

**Comment by HollowMan6** [comment]
Hi @GeoffMurray ! Would you please provide the book source code you use that have this issue for me to investigate, or at least your `book.toml` if it's not open-sourced. Because the error thrown in your case is really weird, and I think the problem may lie in your configuration file. Otherwise, I won't know what caused this.

**Comment by GeoffMurray** [comment]
I've attached the config file. Maybe let me know if you think you still need the source, I could send you the book privately? 

[book.toml.txt](https://github.com/HollowMan6/mdbook-pdf/files/10694348/book.toml.txt)

**Comment by GeoffMurray** [comment]
I should mention, I'm not using your forked mdbook - I was using the standard one, if that makes a difference.

**Comment by HollowMan6** [comment]
Ah Ok, so would you please use my forked version and try that again? I actually have mentioned in the README that this is necessary:

> Initial support for the bookmark/outline of the PDF file has already been available ([mdbook-pdf-outline](https://pypi.org/project/mdbook-pdf-outline/)). It is written in Python and is another backend for mdbook and ***should be used with mdbook-pdf and the [mdbook version](https://github.com/rust-lang/mdBook/pull/1738) mentioned in Common Issues 2*** for fixing the broken links in print.html.

If it's still the case, I will try to test your book.toml file and see what's going on.

**Comment by GeoffMurray** [comment]
Thank you. I will try that.

**Comment by GeoffMurray** [comment]
Ok - I believe I loaded everything correctly, including your specific version of mdbook. I still get what looks like the same error:

2023-02-09 08:15:56 [INFO] (mdbook::renderer): Invoking the "pdf-outline" renderer
Traceback (most recent call last):
  File "/usr/local/bin/mdbook-pdf-outline", line 7, in <module>
    from mdbook_pdf_outline.mdbook_pdf_outline import main
  File "/usr/local/bin/mdbook_pdf_outline.py", line 8
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

Can I send you the files directly?

**Comment by GeoffMurray** [comment]
OK - I'm maybe closer. I think I've screwed up the Python portion of the install somehow. I noticed the /usr/local/bin/mdbook_pdf_outline.py file was corrupt, and contained a bunch of seeming HTML. 

Uninstalled mdbook, deleted the corrupt file, reinstalled it, and now get this. And pip3 is saying pypdf is installed. 

Traceback (most recent call last):
  File "/usr/local/bin/mdbook-pdf-outline", line 7, in <module>
    from mdbook_pdf_outline.mdbook_pdf_outline import main
  File "/usr/local/bin/mdbook_pdf_outline.py", line 16, in <module>
    from pypdf import PdfReader, PdfWriter
ModuleNotFoundError: No module named 'pypdf'

**Comment by HollowMan6** [comment]
Actually I would suggest you to remove most of the content or replace it with something else, just to make sure that you can reproduce with that content is Okay.

I can't find any abnormal things in your book.toml, so I would assume that you do have some syntax error like tag pairing in your book.

**Comment by HollowMan6** [comment]
> OK - I'm maybe closer. I think I've screwed up the Python portion of the install somehow. I noticed the /usr/local/bin/mdbook_pdf_outline.py file was corrupt, and contained a bunch of seeming HTML.
> 
> Uninstalled mdbook, deleted the corrupt file, reinstalled it, and now get this. And pip3 is saying pypdf is installed.
> 
> Traceback (most recent call last): File "/usr/local/bin/mdbook-pdf-outline", line 7, in from mdbook_pdf_outline.mdbook_pdf_outline import main File "/usr/local/bin/mdbook_pdf_outline.py", line 16, in from pypdf import PdfReader, PdfWriter ModuleNotFoundError: No module named 'pypdf'

That's interesting, I don't know what happened, but clearly it should be something related to the environment instead of the code.

**Comment by GeoffMurray** [comment]
Hmmm - still no joy. This is the output of the latest run. It seems to be indicating I've got the critical python bits installed correctly this time. Not sure what to look at next. 

$ pip3 --version
pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
$ pip3 show pypdf
Name: pypdf
Version: 3.4.0
Summary: A pure-python PDF library capable of splitting, merging, cropping, and transforming PDF files
Home-page: None
Author: None
Author-email: Mathieu Fenniak <biziqe@mathieu.fenniak.net>
License: None
Location: /home/gitlab-runner/.local/lib/python3.6/site-packages
Requires: typing-extensions, dataclasses
$ pip3 show mdbook-pdf-outline
Name: mdbook-pdf-outline
Version: 0.1.0
Summary: Tool for generating outlines for PDF files generated by mdbook-pdf.
Home-page: https://github.com/HollowMan6/mdbook-pdf
Author: Hollow Man (Domain Address)
Author-email: hollowman@opensuse.org
License: GPL-3.0-or-later
Location: /home/gitlab-runner/.local/lib/python3.6/site-packages
Requires: pypdf, lxml
Working directory for book: /Document Library Runbooks
Building book from: 
2023-02-09 10:10:37 [INFO] (mdbook::book): Book building has started
Warning: The plantuml plugin was built against version 0.4.25 of mdbook, but we're being called from version 0.4.26
2023-02-09 10:10:38 [INFO] (mdbook::book): Running the html backend
Warning: The plantuml plugin was built against version 0.4.25 of mdbook, but we're being called from version 0.4.26
2023-02-09 10:10:38 [INFO] (mdbook::book): Running the pdf backend
2023-02-09 10:10:38 [INFO] (mdbook::renderer): Invoking the "pdf" renderer
Generating PDF, please be patient...
PDF successfully generated at: /home/gitlab-runner/builds/jsrSNigW/0/gitlabgroup/gitlabproject/public/branch/branchA/Document Library Runbooks/pdf/output.pdf
Warning: The plantuml plugin was built against version 0.4.25 of mdbook, but we're being called from version 0.4.26
2023-02-09 10:10:41 [INFO] (mdbook::book): Running the pdf-outline backend
2023-02-09 10:10:41 [INFO] (mdbook::renderer): Invoking the "pdf-outline" renderer
Traceback (most recent call last):
  File "/usr/local/bin/mdbook-pdf-outline", line 7, in <module>
    from mdbook_pdf_outline.mdbook_pdf_outline import main
ModuleNotFoundError: No module named 'mdbook_pdf_outline.mdbook_pdf_outline'; 'mdbook_pdf_outline' is not a package
2023-02-09 10:10:41 [ERROR] (mdbook::renderer): Renderer exited with non-zero return code.
2023-02-09 10:10:41 [ERROR] (mdbook::utils): Error: Rendering failed
2023-02-09 10:10:41 [ERROR] (mdbook::utils): 	Caused By: The "pdf-outline" renderer failed
Processed: Gitlab Markdown Based Document Library Management RunBooks
Storing entry in /home/gitlab-runner/builds/jsrSNigW/0/gitlabgroup/gitlabproject/public/branch_branchA.html

**Comment by GeoffMurray** [comment]
Ok - I feel like an idiot. The log above clearly showed I somehow ended up with an extra copy of the python in an unexpected location. I cleaned that, and it works!

This is amazing. I'm so sorry to trouble you with all my questions.
