### ISSUE TITLE
I encountered this problem -> the message is too long

### ISSUE THREAD

**Issue by Sunalamye** [HollowMan6/mdbook-pdf#16]
thread '<unnamed>' panicked at 'Unhandled WebSocket error for Chrome #Some(85607): Capacity(MessageTooLong { size: 70050604, max_size: 16777216 })', /Users/suoie/.cargo/registry/src/github.com-1ecc6299db9ec823/mdbook-pdf-headless_chrome-0.1.5/src/browser/transport/web_socket_connection.rs:100:25

**Comment by HollowMan6** [comment]
Error says MessageTooLong? Would you provide the book? Looks like you reached some limit unreasonably.

**Comment by Sunalamye** [comment]
Sorry, I can't give you that info. It's personal and kinda sensitive.

**Comment by HollowMan6** [comment]
Sorry, if you can't, then I won't be able to help you, as I can't reproduce it and all the books in the CI works OK. https://github.com/HollowMan6/mdbook-pdf/actions/runs/4452352690

You can also try to build one of the open sourced mdbook based book in your computer and see if the same problem persist. If it is, then I would suggest like try upgrading the browser version or just use the fetch feature of mdbook-pdf (check README) to have a fully functioning chromium version. If not, then if you want this tool to get it fixed, please find the problem yourself and submit a PR if possible, Thank you!

**Comment by HollowMan6** [comment]
Hi @Sunalamye ! Someone has faced the exact same issue and just to notify you about the update: https://github.com/HollowMan6/mdbook-pdf/issues/17#issuecomment-1477029336

**Comment by Sunalamye** [comment]
Understood, thank you for the information.

**Comment by HollowMan6** [comment]
Hi! mdbook-pdf should now be OK with very large images/pdfs, see https://github.com/HollowMan6/mdbook-pdf/issues/17#issuecomment-1480266623
