### ISSUE TITLE
`mdbook-pdf-outline` doesn't render anything

### ISSUE THREAD

**Issue by deobald** [HollowMan6/mdbook-pdf#18]
Results of `RUST_BACKTRACE=full RUST_LOG=trace mdbook build` are here:

https://gist.github.com/deobald/36e2f95b26371ad825f002010835bfde

`book.toml` is here:

https://gist.github.com/deobald/30451a715c99c765b2636925c1aec366

Repo is here:

https://github.com/endatabas/endb-book

## Description

Running `mdbook_pdf_outline.py` with some debugging print statements, it seems that the calls to `writer.add_outline_item` are never executed. As a result, `book/pdf-outline/output.pdf` does not contain the table of contents as a page at the beginning. I didn't try to diagnose why all the nested conditionals were failing, since I'm guessing that will be far easier for @HollowMan6 

Feel free to remove `[preprocessor.toc]` while debugging -- `pdf-outline` was failing before I added that. I was hoping it could be a workaround, but it's for chapter-level ToCs.

**Comment by HollowMan6** [comment]
Hi! Everything is OK when I tried to generate the outline with your configuration.

[output.pdf](https://github.com/HollowMan6/mdbook-pdf/files/11179796/output.pdf)

so I assume that you didn't use my fork of mdbook for generating the pdf, which I have mentioned in https://github.com/HollowMan6/mdbook-pdf#common-issues
> should be used with mdbook-pdf and **_the https://github.com/rust-lang/mdBook/pull/1738 mentioned in Common Issues 2 for fixing the broken links in print.html_**

You can install that by `cargo install --git https://github.com/HollowMan6/mdBook mdbook`

**Comment by HollowMan6** [comment]
Just updated the explanation in README, sorry if this is causing any confusion like you said in README: https://github.com/endatabas/endb-book/tree/008b39a820366fd6b67fb915a7faabd329e324cb#bugs

Unfortunately I don't know why mdbook upstream is so slow at accepting my PR, hope this can get accepted soon one day. https://github.com/rust-lang/mdBook/pull/1738

**Comment by deobald** [comment]
Ah, I think I may have actually misunderstood what `mdbook-pdf-outline` actually does. I assumed it created an automatic Table of Contents page at the beginning of the PDF. The `output.pdf` you linked doesn't contain that, but it does contain a (sidebar) outline in the PDF viewer. For my own sanity: that's all it's expected to do, correct?

**Comment by HollowMan6** [comment]
Yes, that's correct. Actually there's nothing complicated if you want to create an automatic Table of Contents page at the beginning of the PDF, no need to use any other additional tools, just duplicate your `src/SUMMARY.md` to e.g. `src/TOC.md`, and add a link of that duplicated file `src/TOC.md` into your `src/SUMMARY.md`.

You can use the following script to automate that process.

```bash
echo '- [Table of Content](./TOC.md)' | cat - src/SUMMARY.md > temp && mv temp src/SUMMARY.md
cp src/SUMMARY.md src/TOC.md
echo '# Table of Content' | cat - src/TOC.md > temp && mv temp src/TOC.md
```

> Ah, I think I may have actually misunderstood what `mdbook-pdf-outline` actually does. I assumed it created an automatic Table of Contents page at the beginning of the PDF. The `output.pdf` you linked doesn't contain that, but it does contain a (sidebar) outline in the PDF viewer. For my own sanity: that's all it's expected to do, correct?

**Comment by HollowMan6** [comment]
Hi! For broken links, you can use my fork of mdbook mentioned in common issue 2 to fix it. https://github.com/HollowMan6/mdbook-pdf#common-issues
