### ISSUE TITLE
chrome window shows up when invoking mdbook

### ISSUE THREAD

**Issue by rmantovani68** [HollowMan6/mdbook-pdf#20]
Everytime mdbook is executed 4 empty windows are shown.
Is it possible to hide these windows ?

**Comment by HollowMan6** [comment]
Hi! Thank you for your report. This is an issue related to upstream, let's wait for https://github.com/rust-headless-chrome/rust-headless-chrome/issues/371 to get resolved.

**Comment by HollowMan6** [comment]
I have submitted the PR to fix this: https://github.com/rust-headless-chrome/rust-headless-chrome/pull/391

For mdbook-pdf, now this should get fixed. You can re-install by `cargo install -f mdbook-pdf`.
