### ISSUE TITLE
win10编译失败

### ISSUE THREAD

**Issue by miaomiao1992** [HollowMan6/mdbook-pdf#23]
error: failed to run custom build command for `mdbook-pdf-headless_chrome v0.1.10`

Caused by:
  process didn't exit successfully: `G:/rust-target\release\build\mdbook-pdf-headless_chrome-d501cd4fa29152d7\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Request error: Transport(Transport { kind: Dns, message: Some("resolve dns name 'raw.githubusercontent.com:443'"), url: Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("raw.githubusercontent.com")), port: None, path: "/ChromeDevTools/devtools-protocol/15f524c8f5ce5b317ddcdf5e6f875d6eb8bdac88/json/js_protocol.json", query: None, fragment: None }), source: Some(Os { code: 11004, kind: Uncategorized, message: "请求的名称有效，但是找不到请求的类型的数据。" }) })', C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\auto_generate_cdp-0.4.1\src\compile.rs:1296:14
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panicking.rs:575
     1: core::panicking::panic_fmt
               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\panicking.rs:64
     2: core::result::unwrap_failed
               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\result.rs:1790
     3: core::result::Result<T,E>::expect
     4: auto_generate_cdp::compile::get_types::{{closure}}
     5: auto_generate_cdp::compile::compile_cdp_json
     6: auto_generate_cdp::init
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...

**Comment by HollowMan6** [comment]
I guess you are now in China, since the great firewall censored `raw.githubusercontent.com`, this is something related to https://github.com/mdrokz/auto_generate_cdp#compiling-behind-a-firewall

If you don't have a proxy, try to set the environment variable (e.g. in Powershell):
```bash
$env:DOCS_RS='true'
```

Referring to: https://github.com/mdrokz/auto_generate_cdp/commit/2d0edc61def2561ac927c272967d237d55c628ce

**Comment by efikarl** [comment]
Works for me, respect from the man behind great firewall to you @HollowMan6
