### ISSUE TITLE
Code in titles using gray background

### ISSUE THREAD

**Issue by proski** [HollowMan6/mdbook-pdf#26]
The PDF files produces by mdbook-pdf use gray background for `code` quotes in titles. It's a visual annoyance. The HTML is using white background in the light theme for everything, including titles and code in them, so I would expect the same in PDF. Worse yet, some PDF viewers make that text completely invisible, e.g. ReadEra on Android in the Twilight theme (which is my preferred way of reading Rust books).

I'm using be current mdbook (0.4.32) and mdbook-pdf (0.1.17). I'm running them on MacOS 13.4.1 with Chrome 115.

<img width="1424" alt="rustbook" src="https://github.com/HollowMan6/mdbook-pdf/assets/1317472/29093c16-9f56-4bdc-9790-883cf331df4b">

**Comment by proski** [comment]
I was able to get good results by doing following steps:

* Run `mdbook init --theme` in the Rust book repository
* Restore `book.toml` by running `git checkout book.toml`
* Add an empty `output.pdf` section to `book.toml`
* Edit `theme/css/print.css` and comment out `-webkit-print-color-adjust: exact;`
* Run `mdbook build`

An alternative approach is to adjust `background-color` in the same file. `#666666` is too dark when the foreground is black. `#cccccc` looked better, but I'd rather not see any custom backgrounds.

Changing `print-background` and `theme` under `[output.pdf]` didn't produce good results in any combination.

**Comment by HollowMan6** [comment]
Yeah! Thanks for providing the detailed steps to fix this. Glad you find the issue to discuss with the upstream!

**Comment by proski** [comment]
The issue is fixed in mdbook 0.4.33.
