### ISSUE TITLE
Cargo: mdbook-pdf command not found

### ISSUE THREAD

**Issue by ivakam** [HollowMan6/mdbook-pdf#28]
I've installed mdbook-pdf via `cargo install mdbook-pdf`. I can see the binary in my .cargo folder, but it doesn't show up as a cargo command. Mdbook also errors when running `mdbook build` saying that the pdf backend is not installed.

**Comment by HollowMan6** [comment]
https://doc.rust-lang.org/book/ch14-04-installing-binaries.html

You must haven't added `$HOME/.cargo/bin` to your $PATH, please configure that by referring to Google according to your operating system.
