### ISSUE TITLE
can it make a toc like pandoc?

### ISSUE THREAD

**Issue by oldbotman** [HollowMan6/mdbook-pdf#36]
Can this generate a table of contents (TOC)? Currently, when generating a PDF, I not only need a TOC on the left side, but I also hope that the PDF has a table of contents page.

**Comment by HollowMan6** [comment]
I'm not sure how does toc like in pandoc, but we can of course have a Table of Contents page at the beginning of the PDF. You can check https://github.com/HollowMan6/mdbook-pdf/issues/18#issuecomment-1500819358

For TOC as bookmarks, check Common Issues 3: https://github.com/HollowMan6/mdbook-pdf?tab=readme-ov-file#common-issues

**Comment by oldbotman** [comment]
> I'm not sure how does toc like in pandoc, but we can of course have a Table of Contents page at the beginning of the PDF. You can check [#18 (comment)](https://github.com/HollowMan6/mdbook-pdf/issues/18#issuecomment-1500819358)
> 
> For TOC as bookmarks, check Common Issues 3: https://github.com/HollowMan6/mdbook-pdf?tab=readme-ov-file#common-issues

Thank you for your response, I've looked at this solution and it can achieve the effect I want.
