### ISSUE TITLE
Update mdbook to 0.4.21 and publish to crates.io

### ISSUE THREAD

**Issue by tjni** [HollowMan6/mdbook-pdf#4]
Would it be possible to update `mdbook` to version `0.4.21` and update the release on crates.io? This version contains a fix for https://github.com/rust-lang/mdBook/issues/1860 to enable building using Rust 1.64. In the meantime, I'm creating a patch for this in nixpkgs but would love to be able to pick it up just by updating the version.

**Comment by HollowMan6** [comment]
Updated: https://crates.io/crates/mdbook-pdf/0.1.3

Thanks for the patch of this in nixpkgs in advance by the way!
