### ISSUE TITLE
mdbook-pdf theme

### ISSUE THREAD

**Issue by schwrzstrbn** [HollowMan6/mdbook-pdf#5]
Does it have themes that we can use for the output pdf?

**Comment by HollowMan6** [comment]
Hi! mdbook-pdf is highly dependent on the generated html, so you can set `default-theme` in `[output.html]` to change the output pdf theme.

https://rust-lang.github.io/mdBook/format/configuration/renderers.html#html-renderer-options

**Comment by schwrzstrbn** [comment]
> 

Thanks!

**Comment by schwrzstrbn** [comment]
> Hi! mdbook-pdf is highly dependent on the generated html, so you can set `default-theme` in `[output.html]` to change the output pdf theme.
> 
> https://rust-lang.github.io/mdBook/format/configuration/renderers.html#html-renderer-options

There seems to be a problem with it. It doesn't show the correct theme upon generating a pdf.

**Comment by HollowMan6** [comment]
There shouldn't be any problem. You can check the generated print.html to check if you have set the correct theme.

Also, if you mean changing the background, remember to set `print-background = true` in `[output.pdf]` https://github.com/HollowMan6/mdbook-pdf/blob/main/test_doc/book.toml#L23 

> > Hi! mdbook-pdf is highly dependent on the generated html, so you can set `default-theme` in `[output.html]` to change the output pdf theme.
> > https://rust-lang.github.io/mdBook/format/configuration/renderers.html#html-renderer-options
> 
> There seems to be a problem with it. It doesn't show the correct theme upon generating a pdf.

**Comment by schwrzstrbn** [comment]
> There shouldn't be any problem. You can check the generated print.html to check if you have set the correct theme.
> 
> Also, if you mean changing the background, remember to set `print-background = true` in `[output.pdf]` https://github.com/HollowMan6/mdbook-pdf/blob/main/test_doc/book.toml#L23
> 
> > > Hi! mdbook-pdf is highly dependent on the generated html, so you can set `default-theme` in `[output.html]` to change the output pdf theme.
> > > https://rust-lang.github.io/mdBook/format/configuration/renderers.html#html-renderer-options
> > 
> > 
> > There seems to be a problem with it. It doesn't show the correct theme upon generating a pdf.

Oh I missed that, lemme try it real quick. Thanks!

**Comment by HollowMan6** [comment]
Hi! Just released a new version so that we can separate the html theme with the pdf one. https://github.com/HollowMan6/mdbook-pdf/releases/tag/v0.1.4

**Comment by schwrzstrbn** [comment]
> Hi! Just released a new version so that we can separate the html theme with the pdf one. https://github.com/HollowMan6/mdbook-pdf/releases/tag/v0.1.4

so how does that work? new keyword for the `[output.pdf]`?

**Comment by HollowMan6** [comment]
Yes.
https://github.com/HollowMan6/mdbook-pdf/blob/main/test_doc/book.toml#L24
