### ISSUE TITLE
Page Numbers

### ISSUE THREAD

**Issue by HarshNarayanJha** [HollowMan6/mdbook-pdf#51]
Allow adding page numbers to the bottom of each page, enabled via and option in `book.toml`.

**Comment by HollowMan6** [comment]
This is already supported, just use the footer-template option. An example is 
https://github.com/HollowMan6/mdbook-pdf/blob/c5c48f2235c3ee3bfea805ced83c0a771dac4dd0/test_doc/book.toml#L38

You can read more explanation at https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF
