### ISSUE TITLE
Is there a way to put current date (and maybe time) in the footers for the generated PDFs?

### ISSUE THREAD

**Issue by GeoffMurray** [HollowMan6/mdbook-pdf#7]
It would be helpful so I could try and make the headers and footers more like our regular ones.

**Comment by HollowMan6** [comment]
You can make it show the datetime by assigning the class `date`, like "\<span class=date>\</span>", to the header-template or footer-template https://github.com/HollowMan6/mdbook-pdf/blob/main/test_doc/book.toml#L34

Check https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF for more
